// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package consumer_test

import (
	"context"
	"github.com/VitoNaychev/egt-challenge/persistence/consumer"
	"github.com/VitoNaychev/egt-challenge/persistence/service"
	"github.com/segmentio/kafka-go"
	"sync"
)

// Ensure, that MessageReaderMock does implement consumer.MessageReader.
// If this is not the case, regenerate this file with moq.
var _ consumer.MessageReader = &MessageReaderMock{}

// MessageReaderMock is a mock implementation of consumer.MessageReader.
//
//	func TestSomethingThatUsesMessageReader(t *testing.T) {
//
//		// make and configure a mocked consumer.MessageReader
//		mockedMessageReader := &MessageReaderMock{
//			CommitMessagesFunc: func(ctx context.Context, msgs ...kafka.Message) error {
//				panic("mock out the CommitMessages method")
//			},
//			FetchMessageFunc: func(ctx context.Context) (kafka.Message, error) {
//				panic("mock out the FetchMessage method")
//			},
//		}
//
//		// use mockedMessageReader in code that requires consumer.MessageReader
//		// and then make assertions.
//
//	}
type MessageReaderMock struct {
	// CommitMessagesFunc mocks the CommitMessages method.
	CommitMessagesFunc func(ctx context.Context, msgs ...kafka.Message) error

	// FetchMessageFunc mocks the FetchMessage method.
	FetchMessageFunc func(ctx context.Context) (kafka.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// CommitMessages holds details about calls to the CommitMessages method.
		CommitMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msgs is the msgs argument value.
			Msgs []kafka.Message
		}
		// FetchMessage holds details about calls to the FetchMessage method.
		FetchMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCommitMessages sync.RWMutex
	lockFetchMessage   sync.RWMutex
}

// CommitMessages calls CommitMessagesFunc.
func (mock *MessageReaderMock) CommitMessages(ctx context.Context, msgs ...kafka.Message) error {
	if mock.CommitMessagesFunc == nil {
		panic("MessageReaderMock.CommitMessagesFunc: method is nil but MessageReader.CommitMessages was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msgs []kafka.Message
	}{
		Ctx:  ctx,
		Msgs: msgs,
	}
	mock.lockCommitMessages.Lock()
	mock.calls.CommitMessages = append(mock.calls.CommitMessages, callInfo)
	mock.lockCommitMessages.Unlock()
	return mock.CommitMessagesFunc(ctx, msgs...)
}

// CommitMessagesCalls gets all the calls that were made to CommitMessages.
// Check the length with:
//
//	len(mockedMessageReader.CommitMessagesCalls())
func (mock *MessageReaderMock) CommitMessagesCalls() []struct {
	Ctx  context.Context
	Msgs []kafka.Message
} {
	var calls []struct {
		Ctx  context.Context
		Msgs []kafka.Message
	}
	mock.lockCommitMessages.RLock()
	calls = mock.calls.CommitMessages
	mock.lockCommitMessages.RUnlock()
	return calls
}

// FetchMessage calls FetchMessageFunc.
func (mock *MessageReaderMock) FetchMessage(ctx context.Context) (kafka.Message, error) {
	if mock.FetchMessageFunc == nil {
		panic("MessageReaderMock.FetchMessageFunc: method is nil but MessageReader.FetchMessage was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockFetchMessage.Lock()
	mock.calls.FetchMessage = append(mock.calls.FetchMessage, callInfo)
	mock.lockFetchMessage.Unlock()
	return mock.FetchMessageFunc(ctx)
}

// FetchMessageCalls gets all the calls that were made to FetchMessage.
// Check the length with:
//
//	len(mockedMessageReader.FetchMessageCalls())
func (mock *MessageReaderMock) FetchMessageCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockFetchMessage.RLock()
	calls = mock.calls.FetchMessage
	mock.lockFetchMessage.RUnlock()
	return calls
}

// Ensure, that EventServiceMock does implement consumer.EventService.
// If this is not the case, regenerate this file with moq.
var _ consumer.EventService = &EventServiceMock{}

// EventServiceMock is a mock implementation of consumer.EventService.
//
//	func TestSomethingThatUsesEventService(t *testing.T) {
//
//		// make and configure a mocked consumer.EventService
//		mockedEventService := &EventServiceMock{
//			StoreFunc: func(ctx context.Context, ev service.Event) error {
//				panic("mock out the Store method")
//			},
//		}
//
//		// use mockedEventService in code that requires consumer.EventService
//		// and then make assertions.
//
//	}
type EventServiceMock struct {
	// StoreFunc mocks the Store method.
	StoreFunc func(ctx context.Context, ev service.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Store holds details about calls to the Store method.
		Store []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ev is the ev argument value.
			Ev service.Event
		}
	}
	lockStore sync.RWMutex
}

// Store calls StoreFunc.
func (mock *EventServiceMock) Store(ctx context.Context, ev service.Event) error {
	if mock.StoreFunc == nil {
		panic("EventServiceMock.StoreFunc: method is nil but EventService.Store was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ev  service.Event
	}{
		Ctx: ctx,
		Ev:  ev,
	}
	mock.lockStore.Lock()
	mock.calls.Store = append(mock.calls.Store, callInfo)
	mock.lockStore.Unlock()
	return mock.StoreFunc(ctx, ev)
}

// StoreCalls gets all the calls that were made to Store.
// Check the length with:
//
//	len(mockedEventService.StoreCalls())
func (mock *EventServiceMock) StoreCalls() []struct {
	Ctx context.Context
	Ev  service.Event
} {
	var calls []struct {
		Ctx context.Context
		Ev  service.Event
	}
	mock.lockStore.RLock()
	calls = mock.calls.Store
	mock.lockStore.RUnlock()
	return calls
}
