// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package publisher_test

import (
	"context"
	"github.com/VitoNaychev/egt-challenge/ingestion/publisher"
	"github.com/segmentio/kafka-go"
	"sync"
)

// Ensure, that MessageWriterMock does implement publisher.MessageWriter.
// If this is not the case, regenerate this file with moq.
var _ publisher.MessageWriter = &MessageWriterMock{}

// MessageWriterMock is a mock implementation of publisher.MessageWriter.
//
//	func TestSomethingThatUsesMessageWriter(t *testing.T) {
//
//		// make and configure a mocked publisher.MessageWriter
//		mockedMessageWriter := &MessageWriterMock{
//			WriteMessagesFunc: func(ctx context.Context, msgs ...kafka.Message) error {
//				panic("mock out the WriteMessages method")
//			},
//		}
//
//		// use mockedMessageWriter in code that requires publisher.MessageWriter
//		// and then make assertions.
//
//	}
type MessageWriterMock struct {
	// WriteMessagesFunc mocks the WriteMessages method.
	WriteMessagesFunc func(ctx context.Context, msgs ...kafka.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// WriteMessages holds details about calls to the WriteMessages method.
		WriteMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msgs is the msgs argument value.
			Msgs []kafka.Message
		}
	}
	lockWriteMessages sync.RWMutex
}

// WriteMessages calls WriteMessagesFunc.
func (mock *MessageWriterMock) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	if mock.WriteMessagesFunc == nil {
		panic("MessageWriterMock.WriteMessagesFunc: method is nil but MessageWriter.WriteMessages was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msgs []kafka.Message
	}{
		Ctx:  ctx,
		Msgs: msgs,
	}
	mock.lockWriteMessages.Lock()
	mock.calls.WriteMessages = append(mock.calls.WriteMessages, callInfo)
	mock.lockWriteMessages.Unlock()
	return mock.WriteMessagesFunc(ctx, msgs...)
}

// WriteMessagesCalls gets all the calls that were made to WriteMessages.
// Check the length with:
//
//	len(mockedMessageWriter.WriteMessagesCalls())
func (mock *MessageWriterMock) WriteMessagesCalls() []struct {
	Ctx  context.Context
	Msgs []kafka.Message
} {
	var calls []struct {
		Ctx  context.Context
		Msgs []kafka.Message
	}
	mock.lockWriteMessages.RLock()
	calls = mock.calls.WriteMessages
	mock.lockWriteMessages.RUnlock()
	return calls
}
