// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handler_test

import (
	"context"
	"github.com/VitoNaychev/egt-challenge/ingestion/handler"
	"github.com/VitoNaychev/egt-challenge/ingestion/service"
	"sync"
)

// Ensure, that EventServiceMock does implement handler.EventService.
// If this is not the case, regenerate this file with moq.
var _ handler.EventService = &EventServiceMock{}

// EventServiceMock is a mock implementation of handler.EventService.
//
//	func TestSomethingThatUsesEventService(t *testing.T) {
//
//		// make and configure a mocked handler.EventService
//		mockedEventService := &EventServiceMock{
//			PublishFunc: func(contextMoqParam context.Context, event service.Event) error {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedEventService in code that requires handler.EventService
//		// and then make assertions.
//
//	}
type EventServiceMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(contextMoqParam context.Context, event service.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Event is the event argument value.
			Event service.Event
		}
	}
	lockPublish sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *EventServiceMock) Publish(contextMoqParam context.Context, event service.Event) error {
	if mock.PublishFunc == nil {
		panic("EventServiceMock.PublishFunc: method is nil but EventService.Publish was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Event           service.Event
	}{
		ContextMoqParam: contextMoqParam,
		Event:           event,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(contextMoqParam, event)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedEventService.PublishCalls())
func (mock *EventServiceMock) PublishCalls() []struct {
	ContextMoqParam context.Context
	Event           service.Event
} {
	var calls []struct {
		ContextMoqParam context.Context
		Event           service.Event
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}
