// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/VitoNaychev/egt-challenge/persistence/service"
	"sync"
)

// Ensure, that EventRepositoryMock does implement service.EventRepository.
// If this is not the case, regenerate this file with moq.
var _ service.EventRepository = &EventRepositoryMock{}

// EventRepositoryMock is a mock implementation of service.EventRepository.
//
//	func TestSomethingThatUsesEventRepository(t *testing.T) {
//
//		// make and configure a mocked service.EventRepository
//		mockedEventRepository := &EventRepositoryMock{
//			StoreFunc: func(ctx context.Context, event service.Event) error {
//				panic("mock out the Store method")
//			},
//		}
//
//		// use mockedEventRepository in code that requires service.EventRepository
//		// and then make assertions.
//
//	}
type EventRepositoryMock struct {
	// StoreFunc mocks the Store method.
	StoreFunc func(ctx context.Context, event service.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Store holds details about calls to the Store method.
		Store []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event service.Event
		}
	}
	lockStore sync.RWMutex
}

// Store calls StoreFunc.
func (mock *EventRepositoryMock) Store(ctx context.Context, event service.Event) error {
	if mock.StoreFunc == nil {
		panic("EventRepositoryMock.StoreFunc: method is nil but EventRepository.Store was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event service.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockStore.Lock()
	mock.calls.Store = append(mock.calls.Store, callInfo)
	mock.lockStore.Unlock()
	return mock.StoreFunc(ctx, event)
}

// StoreCalls gets all the calls that were made to Store.
// Check the length with:
//
//	len(mockedEventRepository.StoreCalls())
func (mock *EventRepositoryMock) StoreCalls() []struct {
	Ctx   context.Context
	Event service.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event service.Event
	}
	mock.lockStore.RLock()
	calls = mock.calls.Store
	mock.lockStore.RUnlock()
	return calls
}
