// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/VitoNaychev/egt-challenge/ingestion/service"
	"sync"
)

// Ensure, that PublisherMock does implement service.Publisher.
// If this is not the case, regenerate this file with moq.
var _ service.Publisher = &PublisherMock{}

// PublisherMock is a mock implementation of service.Publisher.
//
//	func TestSomethingThatUsesPublisher(t *testing.T) {
//
//		// make and configure a mocked service.Publisher
//		mockedPublisher := &PublisherMock{
//			PublishFunc: func(contextMoqParam context.Context, event service.Event) error {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedPublisher in code that requires service.Publisher
//		// and then make assertions.
//
//	}
type PublisherMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(contextMoqParam context.Context, event service.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Event is the event argument value.
			Event service.Event
		}
	}
	lockPublish sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *PublisherMock) Publish(contextMoqParam context.Context, event service.Event) error {
	if mock.PublishFunc == nil {
		panic("PublisherMock.PublishFunc: method is nil but Publisher.Publish was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Event           service.Event
	}{
		ContextMoqParam: contextMoqParam,
		Event:           event,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(contextMoqParam, event)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedPublisher.PublishCalls())
func (mock *PublisherMock) PublishCalls() []struct {
	ContextMoqParam context.Context
	Event           service.Event
} {
	var calls []struct {
		ContextMoqParam context.Context
		Event           service.Event
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}
