// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rpc_test

import (
	"context"
	"github.com/VitoNaychev/egt-challenge/persistence/rpc"
	"github.com/VitoNaychev/egt-challenge/persistence/service"
	"sync"
)

// Ensure, that EventServiceMock does implement rpc.EventService.
// If this is not the case, regenerate this file with moq.
var _ rpc.EventService = &EventServiceMock{}

// EventServiceMock is a mock implementation of rpc.EventService.
//
//	func TestSomethingThatUsesEventService(t *testing.T) {
//
//		// make and configure a mocked rpc.EventService
//		mockedEventService := &EventServiceMock{
//			GetFunc: func(ctx context.Context, id string) (service.Event, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]service.Event, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedEventService in code that requires rpc.EventService
//		// and then make assertions.
//
//	}
type EventServiceMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (service.Event, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]service.Event, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet  sync.RWMutex
	lockList sync.RWMutex
}

// Get calls GetFunc.
func (mock *EventServiceMock) Get(ctx context.Context, id string) (service.Event, error) {
	if mock.GetFunc == nil {
		panic("EventServiceMock.GetFunc: method is nil but EventService.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedEventService.GetCalls())
func (mock *EventServiceMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *EventServiceMock) List(ctx context.Context) ([]service.Event, error) {
	if mock.ListFunc == nil {
		panic("EventServiceMock.ListFunc: method is nil but EventService.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedEventService.ListCalls())
func (mock *EventServiceMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
